name: Deploy Content to kaleenbhaiya [b42c641e-bf8d-49a4-997e-f9fd26dd434e]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-b42c641e-bf8d-49a4-997e-f9fd26dd434e.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main-sentinel-deployment ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-b42c641e-bf8d-49a4-997e-f9fd26dd434e.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'baklol'
      workspaceName: 'kaleenbhaiya'
      workspaceId: '2ac29f3c-2ab5-4cab-bf46-ac776374aaef'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule'
      branch: 'main-sentinel-deployment'
      sourceControlId: 'b42c641e-bf8d-49a4-997e-f9fd26dd434e'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_b42c641ebf8d49a4997ef9fd26dd434e }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_b42c641ebf8d49a4997ef9fd26dd434e }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_b42c641ebf8d49a4997ef9fd26dd434e }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_b42c641ebf8d49a4997ef9fd26dd434e }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_b42c641ebf8d49a4997ef9fd26dd434e }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_b42c641ebf8d49a4997ef9fd26dd434e }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_b42c641ebf8d49a4997ef9fd26dd434e }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_b42c641ebf8d49a4997ef9fd26dd434e }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_b42c641ebf8d49a4997ef9fd26dd434e }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-b42c641e-bf8d-49a4-997e-f9fd26dd434e.ps1